/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 *
 *  Model ID: 46f4777b-d622-4e90-8c0c-ddc3e29da906
 *  Generated: 2024-11-05T15:10:24Z
 */


namespace StellaNowSDKDemo.Messages.Models;

public record PhoneNumberModel(
    [property: Newtonsoft.Json.JsonProperty("country_code")] int CountryCode,
    [property: Newtonsoft.Json.JsonProperty("number")] int Number
    );

/*
Generated from:

{
    "createdAt": "2024-11-04 17:22:55",
    "updatedAt": "2024-11-04 17:22:55",
    "id": "46f4777b-d622-4e90-8c0c-ddc3e29da906",
    "name": "phone_number",
    "description": "",
    "fields": [
        {
            "id": "b62568d7-0c9f-4af2-8775-f0a975caf534",
            "name": "country_code",
            "fieldType": {
                "value": "Integer"
            }
        },
        {
            "id": "81a4ef9c-5538-488d-bcbc-2d714aadabe9",
            "name": "number",
            "fieldType": {
                "value": "Integer"
            }
        }
    ]
}
*/