
/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 * 
 *  ID: d3a72099-a3ff-453e-9628-9e8d7dba2714
 *  Generated: 2025-03-18T13:21:41Z
*/

namespace StellaNowSDKDemo.Messages.Models;

public record PhoneNumberModel(
    [property: Newtonsoft.Json.JsonProperty("country_code")] int CountryCode,
    [property: Newtonsoft.Json.JsonProperty("number")] int Number
);


/*
 *  Generated from:
 * {
 *     "createdAt": "2025-02-28 00:25:55",
 *     "updatedAt": "2025-02-28 00:25:55",
 *     "id": "d3a72099-a3ff-453e-9628-9e8d7dba2714",
 *     "name": "phone_number",
 *     "description": "",
 *     "fields": [
 *         {
 *             "id": "20ed506e-0913-44db-ba4a-02f2529caec2",
 *             "name": "country_code",
 *             "fieldType": {
 *                 "value": "Integer"
 *             }
 *         },
 *         {
 *             "id": "b1914044-74ef-4af4-8e40-0a4dd48ea5d0",
 *             "name": "number",
 *             "fieldType": {
 *                 "value": "Integer"
 *             }
 *         }
 *     ]
 * }
*/