name: .Net Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - name: Restore Dependencies
        run: dotnet restore StellaNowSDK.sln
      
      - name: Build
        run: dotnet build StellaNowSDK.sln --configuration Release --no-restore