
/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 * 
 *  ID: 06d014b9-9d56-4c08-a19a-5b5363187f00
 *  Generated: 2025-03-18T13:21:41Z
*/

using StellaNowSDK.Messages;


namespace StellaNowSDKDemo.Messages;

public record StoreReceiptMessage(
    [property: Newtonsoft.Json.JsonIgnore] string patron,
    [property: Newtonsoft.Json.JsonIgnore] string local_shop,
    [property: Newtonsoft.Json.JsonProperty("transaction_id")] string TransactionId
) : StellaNowMessageBase(
    "store_receipt", [
        new EntityType("patron", patron),
        new EntityType("local_shop", local_shop)
    ]);


/*
 *  Generated from:
 * {
 *     "createdAt": "2025-03-11 10:25:26",
 *     "updatedAt": "2025-03-11 10:25:31",
 *     "id": "06d014b9-9d56-4c08-a19a-5b5363187f00",
 *     "name": "store_receipt",
 *     "projectId": "4c9450e5-1a6e-4ab4-8b1d-43e9c2a40714",
 *     "isActive": true,
 *     "description": "",
 *     "fields": [
 *         {
 *             "id": "b049d17d-4f46-46de-92c8-b364ec0754df",
 *             "name": "transaction_id",
 *             "fieldType": {
 *                 "value": "String"
 *             },
 *             "required": true,
 *             "subfields": []
 *         }
 *     ],
 *     "entities": [
 *         {
 *             "id": "5ed0f3c9-e3a1-417c-b0da-277d863d88f1",
 *             "name": "patron"
 *         },
 *         {
 *             "id": "7a4af14f-a75e-4ef2-a7cb-60cdb4979bdd",
 *             "name": "local_shop"
 *         }
 *     ]
 * }
*/