/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 *
 *  Event ID: 95e0f48e-cef7-44f6-bc6e-41125b70ef0a
 *  Generated: 2024-01-16T11:37:34Z
 */

using System.Globalization;
using StellaNowSDK.Messages;

namespace StellaNowSDKDemo.Messages;

public class UserLoginMessage : StellaNowMessageWrapper
{
    public UserLoginMessage(string patronId, DateTime timestamp, int userGroupId)
        : base(
            "user_login",
            new List<EntityType>{ new EntityType("patron", patronId) })
    {
        AddField("patron_id", patronId);
        AddField("timestamp", timestamp.ToString("yyyy-MM-ddTHH:mm:ss.ffffffZ"));
        AddField("user_group_id", userGroupId.ToString());
    }
}

/*
Generated from:

{
    "id": "95e0f48e-cef7-44f6-bc6e-41125b70ef0a",
    "name": "user_login",
    "isActive": true,
    "createdAt": "2024-01-05T10:41:02.538119Z",
    "updatedAt": "2024-01-05T10:51:00.119905Z",
    "description": "",
    "fields": [
        {
            "id": "9ec538cd-addf-4d41-a0a5-ad68c7036dce",
            "name": "patron_id",
            "valueType": "String"
        },
        {
            "id": "d6061096-f099-43b3-bcde-d2c177bbadba",
            "name": "timestamp",
            "valueType": "DateTime"
        },
        {
            "id": "0f9ad9ed-e0be-4492-b128-4a77186f19ab",
            "name": "user_group_id",
            "valueType": "Integer"
        }
    ],
    "entities": [
        {
            "id": "626ae62d-84a8-4546-aca2-95ac27134e4e",
            "name": "patron"
        }
    ]
}
*/