/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 *
 *  Event ID: 75f047b6-5839-40c5-931c-9f2cb5a8382f
 *  Generated: 2023-06-30T13:42:49Z
 */

using System.Globalization;
using StellaNowSDK.Messages;

namespace StellaNowSDKDemo.Messages;

public class UserLoginMessage : StellaNowMessageWrapper
{
    public UserLoginMessage(string userId, DateTime timestamp, string patronId)
        : base(
            "user_login",
            new List<EntityType>{ new EntityType("user", userId) })
    {
        AddField("timestamp", timestamp.ToString("yyyy-MM-ddTHH:mm:ss.ffffffZ"));
        AddField("patron_id", patronId);
    }
}

/*
Generated from:

{
    "id": "75f047b6-5839-40c5-931c-9f2cb5a8382f",
    "name": "user_login",
    "isActive": false,
    "createdAt": "2023-06-30T13:21:09.413792Z",
    "updatedAt": "2023-06-30T13:42:43.624732Z",
    "description": "",
    "fields": [
        {
            "id": "0a31fa18-91e0-4631-8297-abedd0d05323",
            "name": "timestamp",
            "valueType": "DateTime"
        },
        {
            "id": "5c504db9-9d77-418e-9542-ebef07e090f6",
            "name": "patron_id",
            "valueType": "String"
        }
    ],
    "entities": [
        {
            "id": "333b5af8-db88-47e1-91a5-5c457678ff02",
            "name": "user"
        }
    ]
}
*/