/*
 *  This file is auto-generated by StellaNowCLI. DO NOT EDIT.
 *  All rights reserved to Stella Technologies (UK) Limited
 *
 *  Event ID: a12b464f-8254-48dc-96cd-a11a8b1dfefd
 *  Generated: 2023-06-15T10:14:28Z
 */

using StellaNowSDK.Messages;

namespace StellaNowSDKDemo.Messages;

public class UserLoginMessage : StellaNowMessageWrapper
{
    public UserLoginMessage(string patronId, string userId, string timestamp)
        : base(
            "user_login",
            new List<EntityType>{ new EntityType("patron", patronId) })
    {
        AddField("user_id", userId);
        AddField("timestamp", timestamp);
    }
}

/*
Generated from:

{
    "id": "a12b464f-8254-48dc-96cd-a11a8b1dfefd",
    "name": "user_login",
    "isActive": true,
    "createdAt": "2023-06-15T08:51:52.606868Z",
    "updatedAt": "2023-06-15T08:52:02.347409Z",
    "description": "",
    "fields": [
        {
            "id": "1c975ccc-a6ec-40cc-9816-4189c20e36e5",
            "name": "user_id",
            "valueType": "String"
        },
        {
            "id": "8275e065-a90a-4eeb-9419-f101053ec48a",
            "name": "timestamp",
            "valueType": "String"
        }
    ],
    "entities": [
        {
            "id": "b5f6bc10-1728-455d-aff5-9cda0ced9c0b",
            "name": "patron"
        }
    ]
}
*/